[package]
name = "clacker"
version = "0.1.0"
authors = ["u0_a143"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
strum = { version = "*", features = ["derive"] }